### ISSUE TITLE
Split Units

### ISSUE THREAD

**Issue by HerrSchreiber** [fictional-pancake/turbo-spork#1]
Add in something like ctrl+clicking to grab only have the units on a node to prevent having deathballs just running around.

**Comment by riftEmber** [comment]
Noob, you have to use skill to avoid clumping units when you don't want to

**Comment by vpzomtrrfrt** [comment]
So should we do this or close the issue?

**Comment by riftEmber** [comment]
I think table it for now

**Comment by vpzomtrrfrt** [comment]
If "wontfix", then this should just be closed.

**Comment by riftEmber** [comment]
But we still might want to do something about it

**Comment by riftEmber** [comment]
I put that as a joke

**Comment by riftEmber** [comment]
I don't think we are going to do it exactly like this though, that would be too easy
