### ISSUE TITLE
Obnoxious Error Messages

### ISSUE THREAD

**Issue by vpzomtrrfrt** [fictional-pancake/turbo-spork#11]
While it's a perfectly correct statement, it's annoying to have to click it.  Here are some ideas I had about fixing it:
- Automatically deselecting nodes you don't own
- Replacing the dialog box with temporary text on the screen

**Comment by riftEmber** [comment]
Should we just replace all error dialogs with temporary text?

**Comment by vpzomtrrfrt** [comment]
I guess
