### ISSUE TITLE
Games should have a delay before starting

### ISSUE THREAD

**Issue by vpzomtrrfrt** [fictional-pancake/turbo-spork#2]
Currently it's instant, giving the player who started it an unfair advantage

**Comment by riftEmber** [comment]
I'm working on this

**Comment by riftEmber** [comment]
Fixed by:
eb0a1883f400e36fe7bb168389566d9eefc6d2a5 on client and 
fictional-pancake/turbo-spork-server@537ca79d719171cea4231371d42286ba678c60ea on server
